steps:
  # 1. Fix workspace permissions
  - name: 'alpine'
    args: ['chown', '-R', '1000:1000', '/workspace']

  # 2. Compile the Java code
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'compile', '-DskipTests']

  # 3. Run Sonar Scan
  - name: 'sonarsource/sonar-scanner-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
          -Dsonar.projectKey=$_SONAR_PROJECT_KEY \
          -Dsonar.organization=$_SONAR_ORG \
          -Dsonar.sources=src \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=$$SONAR_TOKEN
    secretEnv: ['SONAR_TOKEN']
    
  # 4. Build Docker Image (Use :latest)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO_NAME/$_IMAGE_NAME:latest', '.']

  # 5. Push to Artifact Registry (Use :latest)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO_NAME/$_IMAGE_NAME:latest']

  # 6. FETCH GKE CREDENTIALS (This fixes the localhost:8080 error)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials $_GKE_CLUSTER --region $_GKE_LOCATION --project $PROJECT_ID

  # 7. Deploy to GKE (Use :latest)
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO_NAME/$_IMAGE_NAME:latest' # Must match exactly
      - '--location=$_GKE_LOCATION'
      - '--cluster=$_GKE_CLUSTER'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sonarcloud_token/versions/latest
    env: 'SONAR_TOKEN'

substitutions:
  _SONAR_PROJECT_KEY: "rajwhitehat_demopipeline"
  _SONAR_ORG: "rajwhitehat"
  _AR_HOSTNAME: "asia-south1-docker.pkg.dev"
  _AR_REPO_NAME: "learngke"
  _IMAGE_NAME: "gke-demo"
  _GKE_CLUSTER: "autopilot-cluster-1"
  _GKE_LOCATION: "asia-south1"
  _K8S_YAML_PATH: "k8s/"

options:
  logging: CLOUD_LOGGING_ONLY